config/routes.rb
Rails.application.routes.draw do
  resources :home, only: [] do
    get :search, on: :collection
  end
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def search
    if params[:filters].present?
      api_results = Unsplash::Photo.search(search_params[:filters][:query], params[:page] || 1, 30)
      @results = Kaminari.paginate_array(api_results, total_count: api_results.total_pages).page(params[:page]).per(30)
    else
      @results = []
    end
  end

  private

  def search_params
    params.permit(filters: [:query, :color])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<div class="card">
  <div class="card-body">
    <h5 class="card-title">Search</h5>
    <%= form_tag search_home_index_path, method: :get do %>
      <div class="mb-3"><%= text_field_tag :query, nil, name: 'filters[query]', class: 'form-control' %></div>
      <div class="mb-3">
        <%= label_tag :color, nil, class: 'form-label' %>
        <%= select_tag :color, options_for_select(['black_and_white', 'black', 'white', 'yellow', 'orange', 'red', 'purple', 'magenta', 'green', 'teal', 'blue'].collect { |x| [x.titleize, x]}), include_blank: true ,name: 'filters[color]', class: 'form-control' %>
      </div>
      <div class="mb-3">
        <%= submit_tag 'Search', class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/home/search.html.erb
<div class="row row-cols-3 row-cols-md-3 g-4">
  <% @results.each do |result| %>
    <div class="col">
      <div class="card">
        <%= image_tag result.urls.small, class: 'card-img-top', alt: result.alt_description %>
        <div class="card-body">
          <p class="card-text"><%= result.description %></p>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item"><%= link_to result.user.username, result.user.portfolio_url %></li>
          <li class="list-group-item"><%= result.user.bio %></li>
          <li class="list-group-item"><%= result.likes %> Like(s)</li>
        </ul>
        <div class="card-body">
          <%= link_to 'View', result.links.html, class: 'card-link', target: :_blank %>
          <%= link_to 'Download', result.links.download, class: 'card-link' %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<%= paginate @results, theme: 'bootstrap-5' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UnsplashDemo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>